name: Flutter Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the branch name
        run: echo "Current branch name is ${{ github.ref_name }}"
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true


      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/path_finding/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
